BASE <https://soilhive.ag/LUCAS/topsoil/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX gn: <http://www.geonames.org/ontology#>
PREFIX gsp: <http://www.opengis.net/ont/geosparql#>
PREFIX nuts: <http://dd.eionet.europa.eu/vocabulary/common/nuts/>
PREFIX iso28258: <http://w3id.org/glosis/model/iso28258/2013/>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX glosis_lh: <http://w3id.org/glosis/model/layerhorizon#>
PREFIX glosis_pr: <http://w3id.org/glosis/model/profile#>
PREFIX glosis_sp: <http://w3id.org/glosis/model/siteplot/>
PREFIX cap-parcel: <http://lpis.ec.europa.eu/registry/applicationschema/cap-iacs-parcel#>
PREFIX glosis_cl: <http://w3id.org/glosis/model/codelists/>
PREFIX glosis_proc: <http://w3id.org/glosis/model/procedure#>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX unit: <http://qudt.org/vocab/unit/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
  ?URI a glosis_sp:GL_Site;
  rdfs:label ?label;
  gn:parentADM1 ?parentadm1;
  gn:parentADM2 ?parentadm2;  
  gn:parentADM3 ?parentadm3;
  gn:parentADM3 ?parentadm4 .
} 
FROM <> 
WHERE {
  BIND (URI(CONCAT(?POINTID, '/site' )) AS ?URI)
  BIND (CONCAT("LUCAS #", STR(?POINTID)) AS ?label)
  BIND (IRI(CONCAT("http://dd.eionet.europa.eu/vocabulary/common/nuts/", ?NUTS_0)) AS ?parentadm1)
  BIND (IRI(CONCAT("http://dd.eionet.europa.eu/vocabulary/common/nuts/", ?NUTS_1)) AS ?parentadm2)
  BIND (IRI(CONCAT("http://dd.eionet.europa.eu/vocabulary/common/nuts/", ?NUTS_2)) AS ?parentadm3)
  BIND (IRI(CONCAT("http://dd.eionet.europa.eu/vocabulary/common/nuts/", ?NUTS_3)) AS ?parentadm4)
}
LIMIT 5